env:
  gcp: false

letsencrypt:
  email: iulian@rotaru.fr
  server: https://acme-staging-v02.api.letsencrypt.org/directory

server:
  container:
    image: pweek/api
    version: latest
  service:
    type: NodePort
    port: 1337
  ingress:
    host: api.kalastud.io
    gceIpName: api-public

postgres:
  config:
    databaseName: perfectweek
    databaseUser: perfectweek
    databasePassword: super_strong_password
    databasePort: 5432
  persistence:
    gceVolume: pg-disk
    gceVolumeType: ext4
    volumeSize: 20Gi
    accessMode: ReadWriteOnce
  container:
    image: postgres
    version: latest
  service:
    type: ClusterIP
